name: AWX Check

on:
  pull_request:
    branches:
      - main

jobs:
  awx-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call AWX webhook
        id: call-webhook
        run: |
          exit 0
          exit 1
